# config.yml

recipe: default.v1
language: en
assistant_id: "createl_support_assistant" 

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: LogisticRegressionClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    epochs: 40
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.2
    core_fallback_action_name: "action_kb_search"
    enable_fallback_prediction: True
    restrict_rules: False
    check_for_contradictions: False
